//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMSTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LIMSTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Name: Itraconazole-d9
        ///Use as Internal Standard
        ///Q1/Q3 Masses: 714.50/401.30 Da
        ///
        ///Peak Name: Itraconazole
        ///Internal Standard: Itraconazole-d9
        ///Q1/Q3 Masses: 705.20/392.30 Da
        ///
        ///Fit	Quadratic	Weighting	1  / (x * x)	Iterate	No
        ///a0	0.00117
        ///a1	0.0021
        ///a2	9.2e-008
        ///Correlation coefficient	0.9967
        ///Use Area
        ///
        ///
        ///
        ///Sample Name	Sample ID	Filetype	Sample Desc.	Set Number	Acquisition Method	Date Of Acq.	Rack Type	Rack Number	Vial Position	Plate Type	Plate Number	Filename	Dil.Factor	Weight To Volume Ratio	Sample [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleAnalystExport {
            get {
                return ResourceManager.GetString("SampleAnalystExport", resourceCulture);
            }
        }
    }
}
